steps:
  # Docker Build
  name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/My Project 97586/ancy-100925334/${SHORT_SHA}', '.']
  # Docker Push
  name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/My Project 97586/ancy-100925334/${SHORT_SHA}']
  

# setup cloud sdk


    
images:
  - ##provide image info##
  
options:
    defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
    
substitutions:
  _BUCKET_NAME: 'ancy-bucket'
